---
title: "final project"
author: "KRIS WU"
date: "4/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r,message=FALSE}
library(data.table)
library(XML)
library(stringr)
library(RCurl)
library(dplyr)
library(rvest)
library(tidyverse)
library(tidytext)
library(RColorBrewer)
library(wordcloud)
```

#Webscraping and cleaning
```{r}
#The Best Movies on Netflix Instant (Updated for March, 2019)
url <- "https://www.imdb.com/list/ls056789192/" 
#extract movies titles
title <- url%>%
  read_html()%>%
  html_nodes(xpath = "//h3/a[@href]")%>%
  html_text()
#extract the year movie was released
year <- url%>%
  read_html()%>%
  html_nodes(xpath = "//h3/span[@class ='lister-item-year text-muted unbold']")%>%
  html_text()%>%
  str_extract("\\d\\d\\d\\d")
#extract film's length
time <- url%>%
  read_html()%>%
  html_nodes(xpath = "//span[@class='runtime']")%>%
  html_text()
#extract  film's  genre
genre <- url%>%
  read_html()%>%
  html_nodes(xpath = "//span[@class='genre']")%>%
  html_text()%>%
  str_remove("\n")%>%
  str_remove("            ")
#extract film's rate
rate <- url%>%
  read_html()%>%
  html_nodes(xpath = "//span[@class='ipl-rating-star__rating']")%>%
  html_text()
rate <- rate[seq(1, 2300, by = 23)]
#extract the director of movie
director <- url%>%
  read_html()%>%
  html_nodes(xpath = "//p[@class='text-muted text-small']/a[position()=1]")%>%
  html_text()
#extract the number of votes
vote<- url%>%
  read_html()%>%
  html_nodes(xpath = "//span[@name='nv'][position()=1]")%>%
  html_text()
#extract the gross of movie
#Because some of the movie in the website didn't show their gross
#I need to replace the movie which did not have gross with NA
#However,votes and gross are in the same tag. And I scrapt two string. gross_less only have 87 gross and g has both votes and gross. If g has the symbol $, give the gross[i] with correspond value in gross_less
gross_less <- url%>%
  read_html()%>%
  html_nodes(xpath = "//span[@name='nv'][position()=2]")%>%
  html_text()
g <- url%>%
  read_html()%>%
  html_nodes(xpath = "//p[@class='text-muted text-small'][position()=3]")%>%
  html_text()
gross <- c()
a=1
for(i in 1:100){
  if(str_detect(g[i], "\\$")){
    gross[i]=gross_less[a]
    a = a+1
  }
  else{
    gross[i]=NA
  }
}
#extract the  abstract of movie
abstr <- url%>%
  read_html()%>%
  html_nodes(xpath = "//p[@class][position()=2]")%>%
  html_text()
abstract <- abstr[-1]%>%str_remove("\n    ")
#extract the comment
com <- url%>%
  read_html()%>%
  html_nodes(xpath = "//div[@class='list-description']")%>%
  html_text()
comment <- com[-1]%>%
  str_remove("\n.*")
#generate a dataframe
final <- data.frame("title"=title,"year"=year,"time"=time,"genre"=genre,"rate"=rate,"vote"=vote,"gross"=gross,"director"=director,"comment"=comment,"abstract"=abstract)
final$rate <- as.numeric(as.character(final$rate))
final$comment<- as.character(final$comment)
```

#save a tidy version of data as a csvfile
```{r}
write.csv(final,file="/Users/wuqiying/Desktop/final.csv")
```


```{r}
#group by year and check how the movies are distributed across years
most_year <- final%>%group_by(year)%>%
  summarise(total=n())%>%
  arrange(desc(total))
ggplot(most_year[1:10,],aes(year,total))+geom_bar(stat="identity")

#Rank the movies by their gross income
#Rank the movies by their length

final_num <- final%>%
  mutate(numeric_gross = as.numeric(str_extract(final$gross,'\\d*\\.\\d*')))%>%
  mutate(numeric_time = as.numeric(str_extract(final$time,'\\d*')))
head(final_num%>%
       select(title,numeric_gross)%>%
       arrange(desc(numeric_gross)),5)
head(final_num%>%
       select(title,numeric_time)%>%
       arrange(desc(numeric_time)),5)

#word cloud in comment
word_cloud <- final%>%
  select(comment)%>%
  unnest_tokens(word, comment)%>% 
  anti_join(stop_words) %>%
  count(word, sort = TRUE)
pal <- brewer.pal(8, "Dark2")
wordcloud(word_cloud$word,word_cloud$n,colors=pal)
#comment sentiments
senti <- final%>%
  select(title,comment)%>%
   mutate(linenumber = row_number())%>%
  unnest_tokens(word,comment)%>%
  inner_join(get_sentiments("bing"))%>%
  count(title,index = linenumber,sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
ggplot(senti, aes(index, sentiment)) +
  geom_bar(alpha = 0.8, stat = "identity", show.legend = FALSE)
senti[which(senti$sentiment<0),]

#


```

